### ISSUE TITLE
Labelling 

### ISSUE THREAD

**Issue by kmpape** [georgeoshardo/SyMBac#37]
Hello Georgeos,

I was making some progress with our software and wanted to use SyMBac to generate some test sets for our tracking algorithm. I ran `my_simulation.run_simulation` and `my_simulation.draw_simulation_OPL` and plotted some of the masks. I got some results I did not expect and wanted your advice on how to change parts of the code to suit our needs.

1. Cell Division: The cells grow from top to bottom. In mother machine devices, the mother cell is usually fixed. I noticed that after a cell division, it is always the top cell that gets a new ID. Would it be possible to change this behaviour or to allow the rule to be specified by an argument? 
2. Unique IDs: I noticed that if there are $N$ cells in a frame, the IDs always go from $1,\dots,N$. Would it be possible to keep unique IDs? E.g. in the image below, in the transition from $t=34$ to $t=34$, the cell IDs of the 3 top cells are decremented, whereas it would be great if they could keep their IDs (3, 2, 4).

Thank you for your help!

![weird_labels_3](https://github.com/georgeoshardo/SyMBac/assets/43885041/2ec392fa-4d37-4b29-a01c-de6128da7df6)

**Comment by georgeoshardo** [comment]
Hi Idris 
Nice to hear from you
Regarding the labelling first: you can just rotate each mask 180 degrees (2x `np.rot90()`) and then relabel using `skimage.measure.label`, this will make the "top" call mask always have a value of 1. 

Regarding unique cell IDs, it is something that is already possible, since the entire cell lineage is actually saved in the simulation (as we use it to train lineage tracking algorithms). I believe in the cell properties output, where you can find the `Cell` objects, each one of the objects has a `mother` and `daughter` property (maybe only a `mother` property though, I will check later.) 
That should be enough to generate a unique ID, since you will be able to reconstruct the whole lineage tree.

We are working on a SyMBac 2 at the moment, which will feature full CLI access, a better API, and hopefully more stable physics engine, so I would also like to hear from what else you're doing so that while I code it up I can take into account the feedback from other users.

**Comment by georgeoshardo** [comment]
@erezli do you have any code which allows lineage reconstruction from SyMBac cell outputs?

**Comment by georgeoshardo** [comment]
@kmpape I'm hoping that my rewrite will also address this, keeping a unique ID for each cell.

**Comment by georgeoshardo** [comment]
Fixed in https://github.com/georgeoshardo/SyMBac/commit/a976458a4e3db5c293a2a6815803b705e7b42a9d!
